## makeCacheMatrix(x) and cacheSolve() work together to provide a method to
## solve for the inverse of a matrix with solution caching to expedite repeated
## requirements to solve for the same inverse.
##
## Chris Symons 6/05/2020

## makeCacheMatrix(x) returns a list (of functions) which shoudl be assigned to
## some working variable, which should then be used as an argument to
## cacheSolve() in solving for the inverse of matrix x.

makeCacheMatrix <- function(x = numeric()) {
        m <- NULL
        set <- function(y) {
                x <<- y
                m <<- NULL
        }
        get <- function() x
        setSolve <- function(solve) m <<- solve
        getSolve <- function() m
        list(set = set, get = get,
             setSolve = setSolve,
             getSolve = getSolve)
}

## cacheSolve() takes as its argument a list x of the type generated by
## makeCacheMatrix() and solves and returns the inverse of the matrix originally
## passed to makeCacheMatrix()

cacheSolve <- function(x, ...) {
        m <- x$getSolve()
        if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        data <- x$get()
        m <- solve(data, ...)
        x$setSolve(m)
        m
}
